### PR TITLE
Ship project in Docker

### PR DESCRIPTION
**Pull request by FranckErnewein**
in order to run it easly
AND run integration test

### CODE REVIEW

**Comment by FranckErnewein** [comment]
@rehia integration tests should be
- in `/integration/` 
- in  `/test/integration/`
- elsewhere ?

**Comment by FranckErnewein** [comment]
@dandreit could confirm that for now you use this docker image of geonames `jumplead/geonames-server` https://hub.docker.com/r/jumplead/geonames-server/ ?

**Comment by FranckErnewein** [comment]
Require to provide as a lib first https://github.com/lightstream-company/geonames/pull/2

**Comment by dandreit** [comment]
- [x] Pull request #2 merged
- [x] Conflicts solved
- [x] Merging PR #1

**Pull request merged**
